<?xml version="1.0" encoding="utf-8"?><Database Name="GoodCombinationForSnowMan" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\GoodCombinationForSnowMan.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="SnowMan.Properties.Settings" SettingsPropertyName="GoodCombinationForSnowManConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SaveGoodCombination" Member="SaveGoodCombinations">
    <Type Name="SaveGoodCombination">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FillColor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BorderColor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>